sudo: required

language: python

services:
  - docker

env:
  - LIBRARY=annoy
  - LIBRARY=datasketch
  - LIBRARY=dolphinn
  - LIBRARY=faiss
  - LIBRARY=falconn
  - LIBRARY=flann
  - LIBRARY=kgraph
  - LIBRARY=nearpy
  - LIBRARY=nmslib
  - LIBRARY=panns
  - LIBRARY=rpforest
  - LIBRARY=sklearn

before_install:
  - python create_dataset.py --dataset random-xs-10-angular
  - bash install.sh

script:
  - python run.py --docker-tag ann-benchmarks-${LIBRARY} --max-n-algorithms 1 --dataset random-xs-10-angular
