sudo: required

language: python

services:
  - docker

env:
  - ALGORITHM=annoy
  - ALGORITHM=faiss
  - ALGORITHM=kgraph
  - ALGORITHM=rpforest

before_install:
  - bash install.sh

script:
  - echo TODO
