sudo: required

language: python

services:
  - docker

env:
  - LIBRARY=annoy
  - LIBRARY=dolphinn
  - LIBRARY=faiss
  - LIBRARY=falconn
  - LIBRARY=kgraph
  - LIBRARY=nmslib
  - LIBRARY=panns
  - LIBRARY=rpforest

before_install:
  - bash install.sh

script:
  - echo TODO
