float:
  any:
  - base_args: ['@metric']
    constructor: PGVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector
    name: pgvector
    run_groups:
      pgvector:
        arg_groups: []
        args: [[100, 200, 400, 1000, 2000, 4000]]
        query_args: [[1, 2, 4, 10, 20, 40, 100]]
