float:
  any:
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant
    run_groups:
      default:
        arg_groups: []
        args: [[true, false]]
        query_args: [[null, 8, 16, 32, 64, 128, 256]]
