float:
  any:
  - base_args: {}
    constructor: DolphinnPy
    disabled: true
    docker_tag: ann-benchmarks-dolphinn
    module: ann_benchmarks.algorithms.dolphinnpy
    name: DolphinnPy
    run_groups:
      base:
        arg_groups: []
        args: [[10, 50, 100, 200, 1000, 2000]]
        query_args: []
