float:
  any:
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusFLAT
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-flat
      run_groups:
        FLAT:
          args:
            placeholder: [0]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFFLAT
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfflat
      run_groups:
        IVFFLAT:
          args:
            nlist: [32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]
          query_args: 
            [[10, 15, 20, 25, 30]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFSQ8
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfsq8
      run_groups:
        IVFSQ8:
          args:
          args:
            nlist: [32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]
          query_args: 
            [[10, 15, 20, 25, 30]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusIVFPQ
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-ivfpq
      run_groups:
        IVFPQ:
          args:
            nlist: [32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]
            m: [2, 4]
          query_args:
            [[10, 15, 20, 25, 30]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusHNSW
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-hnsw
      run_groups:
        HNSW:
          args:
            M: [4, 8, 12, 16, 24, 36, 48, 64, 96]
            efConstruction: [200, 500]
          query_args:
            [[10, 15, 20, 25, 30, 35, 40, 50, 60, 80, 120, 200, 400]]
    - base_args: ["@metric", "@dimension"]
      constructor: MilvusSCANN
      disabled: false
      docker_tag: ann-benchmarks-milvus
      module: ann_benchmarks.algorithms.milvus
      name: milvus-scann
      run_groups:
        SCANN:
          args:
            nlist: [32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]
          query_args:
            [[10, 15, 20, 25, 30]]
