float:
  any:
  - base_args: ['@metric']
    constructor: BallTree
    disabled: true
    docker_tag: ann-benchmarks-sklearn
    module: ann_benchmarks.algorithms.balltree
    name: ball
    run_groups:
      ball:
        arg_groups: []
        args: [[10, 20, 40, 100, 200, 400, 1000]]
        query_args: []
