bit:
  jaccard:
  - base_args: ['@metric']
    constructor: BruteForceBLAS
    disabled: false
    docker_tag: ann-benchmarks-sklearn
    module: ann_benchmarks.algorithms.bruteforce
    name: bf
    run_groups:
      base:
        arg_groups: []
        args: {}
        query_args: []
float:
  any:
  - base_args: ['@metric']
    constructor: BruteForce
    disabled: true
    docker_tag: ann-benchmarks-sklearn
    module: ann_benchmarks.algorithms.bruteforce
    name: bruteforce
    run_groups:
      empty:
        arg_groups: []
        args: []
        query_args: []
  - base_args: ['@metric']
    constructor: BruteForceBLAS
    disabled: false
    docker_tag: ann-benchmarks-sklearn
    module: ann_benchmarks.algorithms.bruteforce
    name: bruteforce-blas
    run_groups:
      empty:
        arg_groups: []
        args: []
        query_args: []
